{{- if .Values.secrets }}
# Encrypted for this namespace and name only ("strict" scope): copying the
# ciphertext to another service does not decrypt it.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "service.name" . }}-secrets
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml .Values.secrets | nindent 4 }}
  template:
    metadata:
      name: {{ include "service.name" . }}-secrets
      labels:
        {{- include "service.labels" . | nindent 8 }}
{{- end }}
